pipeline:

  my-build:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://localhost:2375
    commands:
      - docker build -t <image_name> .
    when:
      branch: master
      event: push
